samples/jruby_rails4/config/routes.rb
JrubyRails4::Application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end

end

samples/jruby_rails4/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

samples/jruby_rails4/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

samples/jruby_rails4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

samples/jruby_rails4/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

end

samples/jruby_rails4/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :text))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def create
    @post = Post.new(params[:post].permit(:title, :text))

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

samples/jruby_rails4/app/helpers/application_helper.rb
module ApplicationHelper
end

samples/jruby_rails4/app/helpers/comments_helper.rb
module CommentsHelper
end

samples/jruby_rails4/app/helpers/posts_helper.rb
module PostsHelper
end

samples/jruby_rails4/app/views/comments/_comment.html.erb
<div class="comment">
  <%= comment.commenter %> says:
  </br>
  <%= comment.body %>
</div>

samples/jruby_rails4/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

samples/jruby_rails4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JrubyRails4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

samples/jruby_rails4/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

samples/jruby_rails4/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

samples/jruby_rails4/app/views/posts/index.html.erb
<h1>Listing posts</h1>
<%= link_to 'New post', new_post_path %>

<% @posts.each do |post| %>
  <div class="post">
    <h3>
      <%= link_to post.title, post_path(post) %>
    </h3>

    <div><%= post.text %></div>
  </div>
<% end %>

samples/jruby_rails4/app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

samples/jruby_rails4/app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>

<p>
  <%= @post.text %>
</p>


<h4>Comments</h2>
<%= render @post.comments %>

<h4>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>